###s
GET   http://localhost:8000/api/users/601d99a921caec28d085a2d9

###
POST    http://localhost:8000/api/users/clean
Content-Type: application/json

{
    "room" : "1234" , 
    "votation" : true , 
    "score" : 10
}
###
POST  http://localhost:8000/api/users
Content-Type: application/json

{
    "name" : "Bart" , 
    "votation" : true , 
    "score" : 10
}
###
GET   http://localhost:8000/api/room
###
GET   http://localhost:8000/api/room/occupied


###
POST  http://localhost:8000/api/room
Content-Type: application/json

{
    "name" : "FirstRoom" , 
    "users" : 3 , 
    "active" : true
}

###
POST  http://localhost:8000/api/system
Content-Type: application/json

{
    "name" : "Fibonacci-Modified" , 
    "numbers" : [0,0.5,1,2,3,5,8,13,20,40,100]
  
}

###
GET   http://localhost:8000/api/system


###
GET   http://localhost:8000/api/system/Fibonacci

###
GET   http://localhost:8000/api/room/5400

